load_data:
  raw_data_csv: data/raw/insurance.csv
  process_data_csv: data/processed/processed.csv

split_data:
  train_path: data/processed/train_insurance.csv
  test_path: data/processed/test_insurance.csv
  split_ratio: 0.250

model_dirs: saved_models

webapp_model: model.pkl